BOOT_PART="/dev/sda1"
SWAP_PART="/dev/sda2"
ROOT_PART="/dev/sda3"

TIMEZONE=""
LOCALE="en_US.UTF-8"
KEYMAP="us"
HOSTNAME="archlinux"

USERNAME=""
USER_PASSWORD=""
ROOT_PASSWORD=""

EXTRA_PACKAGES="fastfetch"
